import os
import sys
import json
import joblib
from datetime import datetime

current_dir = os.path.dirname(os.path.abspath(__file__))
project_root = os.path.dirname(current_dir)
sys.path.append(project_root)

MODELS_DIR = os.path.join(project_root, 'models')

def detect_model_type(version_path, version_name):
    """Detect model type from folder contents and name"""
    # Check for specific model files
    if os.path.exists(os.path.join(version_path, 'model_xgb.joblib')):
        return 'xgboost'
    elif os.path.exists(os.path.join(version_path, 'model_rf.joblib')):
        return 'random_forest'
    elif os.path.exists(os.path.join(version_path, 'model.keras')):
        return 'dnn'
    elif os.path.exists(os.path.join(version_path, 'ensemble_config.json')):
        return 'ensemble'
    
    # Fallback: check folder name
    name_lower = version_name.lower()
    if 'xgb' in name_lower or 'xgboost' in name_lower:
        return 'xgboost'
    elif 'rf' in name_lower or 'forest' in name_lower:
        return 'random_forest'
    elif 'ensemble' in name_lower:
        return 'ensemble'
    elif 'dnn' in name_lower:
        return 'dnn'
    
    return 'unknown'

def get_num_classes(version_path):
    """Try to get number of classes from label encoder"""
    encoder_path = os.path.join(version_path, 'label_encoder.joblib')
    if os.path.exists(encoder_path):
        try:
            encoder = joblib.load(encoder_path)
            return len(encoder.classes_)
        except:
            pass
    return None

def create_metadata(version_path, version_name):
    """Create metadata.json for a model version"""
    
    model_type = detect_model_type(version_path, version_name)
    num_classes = get_num_classes(version_path)
    
    # Try to extract timestamp from folder name (e.g., v025_20260203_030725_...)
    trained_at = datetime.now().isoformat()
    parts = version_name.split('_')
    if len(parts) >= 3 and len(parts[1]) == 8 and len(parts[2]) == 6:
        try:
            # Format: YYYYMMDD_HHMMSS
            date_str = parts[1]
            time_str = parts[2]
            dt = datetime.strptime(f"{date_str}{time_str}", "%Y%m%d%H%M%S")
            trained_at = dt.isoformat()
        except:
            pass
    
    metadata = {
        'version': version_name,
        'model_type': model_type,
        'trained_at': trained_at,
        'test_accuracy': 0.0,  # Placeholder - unknown
        'test_loss': None,
        'num_classes': num_classes,
        'num_features': None,  # Unknown
        'train_samples': None,  # Unknown
        'note': 'Metadata auto-generated by fix_metadata.py'
    }
    
    return metadata

def fix_all_metadata():
    """Scan models directory and create missing metadata files"""
    
    if not os.path.exists(MODELS_DIR):
        print(f"[ERROR] Models directory not found: {MODELS_DIR}")
        return
    
    print("\n" + "="*60)
    print("  METADATA FIXER")
    print("="*60)
    print(f"Scanning: {MODELS_DIR}\n")
    
    fixed_count = 0
    skipped_count = 0
    
    for item in os.listdir(MODELS_DIR):
        item_path = os.path.join(MODELS_DIR, item)
        
        # Only process directories starting with 'v'
        if not os.path.isdir(item_path) or not item.startswith('v'):
            continue
        
        metadata_path = os.path.join(item_path, 'metadata.json')
        
        if os.path.exists(metadata_path):
            print(f"  [OK] {item} - metadata exists, skipping")
            skipped_count += 1
            continue
        
        # Create metadata
        print(f"  > {item} - creating metadata...")
        metadata = create_metadata(item_path, item)
        
        with open(metadata_path, 'w') as f:
            json.dump(metadata, f, indent=2)
        
        print(f"     Model Type: {metadata['model_type']}")
        print(f"     Classes: {metadata['num_classes']}")
        print(f"     [OK] Created: metadata.json")
        fixed_count += 1
    
    print("\n" + "="*60)
    print(f"  SUMMARY")
    print("="*60)
    print(f"  Fixed: {fixed_count}")
    print(f"  Skipped: {skipped_count}")
    print("="*60 + "\n")
    
    if fixed_count > 0:
        print("[INFO] Run model_manager.py again to see all models!")

if __name__ == "__main__":
    fix_all_metadata()
